# EDA

Para poder empezar el EDA primero se hará la limpieza de datos

## Inicio de Limpieza de datos

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Exploración de la base de datos

In [2]:
df = pd.read_csv('../Data/TEC Loadboard - BD V1 (1).csv')
df.head()

C:\Users\santo\AppData\Local\Temp\ipykernel_4948\1447392260.py:1: DtypeWarning: Columns (0: Johana, 1: Stop de Frontera 3 ( Ciudad / Estado )) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/TEC Loadboard - BD V1 (1).csv')

,VXS,LINK,Cliente,Carrier,ORIGEN,DESTINO,DIVISION,RANGO,FLUJO,ESTATUS,...,Número de Comentarios Ops Rep,Origen Tardio,Destino Tardio,Fecha Subida Factura Proveedor,All in rate venta,All in rate costo,Accesorial venta,Accesorial costo,Cantidad Accesoriales Venta,Cantidad Accesoriales Costo
0,TLG-00001,https://zenitt.xyz/admin/create-load?id=8803,Cliente 232,Carrier 301,"Los Mochis, Sinaloa","Saltillo, Coahuila de Zaragoza",National,Contracted,Northbound,Cancelled,...,NaN,0,0,NaN,"$355,000.00","$25,000.00",$0.00,$0.00,0.0,0.0
1,TMP-00000,https://zenitt.xyz/admin/create-load?id=4187,Cliente 30,NaN,NaN,NaN,National,Contracted,NaN,Cancelled,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TMP-00001,https://zenitt.xyz/admin/create-load?id=4188,Cliente 30,NaN,NaN,NaN,National,Contracted,NaN,Cancelled,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TMP-00002,https://zenitt.xyz/admin/create-load?id=4189,Cliente 30,NaN,NaN,NaN,National,Contracted,Import,Cancelled,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TMP-00003,https://zenitt.xyz/admin/create-load?id=4190,Cliente 30,NaN,"Ramos Arizpe, Coahuila de Zaragoza","San Pedro Tlaquepaque, Jalisco",National,Contracted,Import,Cancelled,...,NaN,0,0,NaN,"$15,000.00",$0.00,$0.00,$0.00,0.0,0.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8714 entries, 0 to 8713
Data columns (total 78 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   VXS                                     8714 non-null   str
 1   LINK                                    8714 non-null   str
 2   Cliente                                 8714 non-null   str
 3   Carrier                                 7835 non-null   str
 4   ORIGEN                                  8423 non-null   str
 5   DESTINO                                 8423 non-null   str
 6   DIVISION                                8497 non-null   str
 7   RANGO                                   8406 non-null   str
 8   FLUJO                                   7546 non-null   str
 9   ESTATUS                                 8714 non-null   str
 10  VENTA                                   8417 non-null   str
 11  COSTO                                   8417 non-null   str
 12  UTILIDAD                                8340 non-null   str
 13  VENTA EN MXN                            8417 non-null   str
 14  COSTO EN MXN                            8417 non-null   str
 15  UTILIDAD EN MXN                         8340 non-null   str
 16  FECHA CREACIÓN                          8714 non-null   str
 17  Fecha programada de recolección         8383 non-null   str
 18  Fecha programada de entrega             8386 non-null   str
 19  Fecha Booked                            8042 non-null   str
 20  Fecha Dispatched                        7652 non-null   str
 21  Fecha At Shipper                        7635 non-null   str
 22  Fecha Picked Up                         7604 non-null   str
 23  Fecha At Border                         7578 non-null   str
 24  Fecha In Transit                        7532 non-null   str
 25  Fecha At Delivery                       7503 non-null   str
 26  Fecha Delivered                         7499 non-null   str
 27  Fecha Ready to Invoice                  6058 non-null   str
 28  FECHA DE FACTURA                        7324 non-null   str
 29  OTP                                     8714 non-null   int64
 30  OTD                                     8714 non-null   int64
 31  CXB                                     8714 non-null   int64
 32  National                                8714 non-null   int64
 33  SALES REP                               8005 non-null   str
 34  OPS REP                                 8712 non-null   str
 35  CARRIER REP                             8033 non-null   str
 36  Johana                                  482 non-null    str
 37  AFTERHOURS REP                          4871 non-null   str
 38  SALES LEAD                              1640 non-null   str
 39  OPS LEAD                                8712 non-null   str
 40  CARRIER LEAD                            8022 non-null   str
 41  SALES MANAGER                           8673 non-null   str
 42  OPS MANAGER                             8712 non-null   str
 43  CARRIER MANAGER                         8033 non-null   str
 44  Cinthia                                 0 non-null      float64
 45  MAIL SALES REP                          8684 non-null   str
 46  MAIL OPS REP                            8712 non-null   str
 47  MAIL CARRIER REP                        8033 non-null   str
 48  MAIL AFTERHOURS REP                     4871 non-null   str
 49  MAIL SALES LEAD                         1640 non-null   str
 50  MAIL OPS LEAD                           8712 non-null   str
 51  MAIL CARRIER LEAD                       8022 non-null   str
 52  MAIL SALES MANAGER                      8673 non-null   str
 53  MAIL OPS MANAGER                        8712 non-null   str
 54  Numero de Comentarios                   46 non-null     float64
 55  MAIL CARRIER MANAGER                    8033 non-null   str
 56  Stop de Frontera 1 ( Ciudad / Estado )  530 non-null    str
 57  Stop de Frontera 2 ( Ciudad / Estado )  62 non-null     str
 58  Stop de Frontera 3 ( Ciudad / Estado )  9 non-null      str
 59  Billing Ref                             0 non-null      float64
 60  PU Number                               0 non-null      float64
 61  Accesorios                              0 non-null      float64
 62  Razón de cancelación                    757 non-null    str
 63  Venta Perdida                           8714 non-null   int64
 64  Número de factura                       7324 non-null   str
 65  Tipo de Equipo                          8202 non-null   str
 66  Total Comentarios                       8714 non-null   int64
 67  Calificación del servicio del carrier   8714 non-null   str
 68  Número de Comentarios Ops Rep           46 non-null     float64
 69  Origen Tardio                           8714 non-null   int64
 70  Destino Tardio                          8714 non-null   int64
 71  Fecha Subida Factura Proveedor          3595 non-null   str
 72  All in rate venta                       8417 non-null   str
 73  All in rate costo                       8417 non-null   str
 74  Accesorial venta                        8417 non-null   str
 75  Accesorial costo                        8417 non-null   str
 76  Cantidad Accesoriales Venta             8417 non-null   float64
 77  Cantidad Accesoriales Costo             8417 non-null   float64
dtypes: float64(8), int64(8), str(62)
memory usage: 5.2 MB

In [4]:
# ver todas las columnas del dataset
df.columns

Index(['VXS', 'LINK', 'Cliente', 'Carrier', 'ORIGEN', 'DESTINO', 'DIVISION',
       'RANGO', 'FLUJO', 'ESTATUS', 'VENTA', 'COSTO', 'UTILIDAD',
       'VENTA EN MXN', 'COSTO EN MXN', 'UTILIDAD EN MXN', 'FECHA CREACIÓN',
       'Fecha programada de recolección', 'Fecha programada de entrega',
       'Fecha Booked', 'Fecha Dispatched', 'Fecha At Shipper',
       'Fecha Picked Up', 'Fecha At Border', 'Fecha In Transit',
       'Fecha At Delivery', 'Fecha Delivered', 'Fecha Ready to Invoice',
       'FECHA DE FACTURA', 'OTP', 'OTD', 'CXB', 'National', 'SALES REP',
       'OPS REP', 'CARRIER REP', 'Johana', 'AFTERHOURS REP', 'SALES LEAD',
       'OPS LEAD', 'CARRIER LEAD', 'SALES MANAGER', 'OPS MANAGER',
       'CARRIER MANAGER', 'Cinthia', 'MAIL SALES REP', 'MAIL OPS REP',
       'MAIL CARRIER REP', 'MAIL AFTERHOURS REP', 'MAIL SALES LEAD',
       'MAIL OPS LEAD', 'MAIL CARRIER LEAD', 'MAIL SALES MANAGER',
       'MAIL OPS MANAGER', 'Numero de Comentarios', 'MAIL CARRIER MANAGER',
       'Stop de Frontera 1 ( Ciudad / Estado )',
       'Stop de Frontera 2 ( Ciudad / Estado )',
       'Stop de Frontera 3 ( Ciudad / Estado )', 'Billing Ref', 'PU Number',
       'Accesorios', 'Razón de cancelación', 'Venta Perdida',
       'Número de factura', 'Tipo de Equipo', 'Total Comentarios',
       'Calificación del servicio del carrier',
       'Número de Comentarios Ops Rep', 'Origen Tardio', 'Destino Tardio',
       'Fecha Subida Factura Proveedor', 'All in rate venta',
       'All in rate costo', 'Accesorial venta', 'Accesorial costo',
       'Cantidad Accesoriales Venta', 'Cantidad Accesoriales Costo'],
      dtype='str')

In [5]:
# verificar valores nulos de cada columna
df.isnull().sum()

VXS                              0
LINK                             0
Cliente                          0
Carrier                        879
ORIGEN                         291
                              ...
All in rate costo              297
Accesorial venta               297
Accesorial costo               297
Cantidad Accesoriales Venta    297
Cantidad Accesoriales Costo    297
Length: 78, dtype: int64

### Eliminar columnas y filas no necesarias

In [6]:
df["Johana"].unique()

<StringArray>
[        nan, 'VXS-06374', 'VXS-06511', 'VXS-06517', 'VXS-06518', 'VXS-06525',
 'VXS-06541', 'VXS-06542', 'VXS-06543', 'VXS-06544',
 ...
 'VXS-09581', 'VXS-09603', 'VXS-09652', 'VXS-09760', 'VXS-09829', 'VXS-09859',
 'VXS-09884', 'VXS-09957', 'VXS-10197', 'VXS-10390']
Length: 483, dtype: str

In [7]:
# contar los valores de la columna "Johana" cuando existe algun dato en la columna "Razón de cancelación"

df[df["Razón de cancelación"].notnull()]["VXS"].value_counts()

VXS
TLG-00001    1
TMP-00000    1
TMP-00001    1
TMP-00002    1
TMP-00003    1
            ..
VXS-14740    1
VXS-14757    1
VXS-14778    1
VXS-14789    1
VXS-14790    1
Name: count, Length: 757, dtype: int64

In [8]:
# Verificar si CXB y National son iguales
df[df["CXB"] == df["National"]].value_counts()

Series([], Name: count, dtype: int64)

In [9]:
# Eliminar las columnas de Joahana y cintia
data = df.drop(columns=["Johana", "Cinthia"])

In [10]:
# Eliminar las columnas que tengan la palabra "MAIL"
data = data.drop(columns=[col for col in data.columns if "MAIL" in col])

In [11]:
df = data.copy()

In [12]:
# Si en la columna "ESTATUS" aparece "Cancelled" eliminar esa fila
df = df[df["ESTATUS"] != "Cancelled"]

In [13]:
#Mostrar solo las columnas con valores nulos y cuantos valores nulos tienen
df.isnull().sum()[df.isnull().sum() > 0]

Carrier                                    403
ORIGEN                                     146
DESTINO                                    146
DIVISION                                   143
RANGO                                      218
FLUJO                                      946
VENTA                                      147
COSTO                                      147
UTILIDAD                                   222
VENTA EN MXN                               147
COSTO EN MXN                               147
UTILIDAD EN MXN                            222
Fecha programada de recolección            167
Fecha programada de entrega                167
Fecha Booked                               196
Fecha Dispatched                           309
Fecha At Shipper                           308
Fecha Picked Up                            335
Fecha At Border                            360
Fecha In Transit                           403
Fecha At Delivery                          431
Fecha Delivered                            433
Fecha Ready to Invoice                    1861
FECHA DE FACTURA                           596
SALES REP                                  234
OPS REP                                      2
CARRIER REP                                207
AFTERHOURS REP                            3475
SALES LEAD                                6341
OPS LEAD                                     2
CARRIER LEAD                               216
SALES MANAGER                               32
OPS MANAGER                                  2
CARRIER MANAGER                            207
Numero de Comentarios                     7870
Stop de Frontera 1 ( Ciudad / Estado )    7425
Stop de Frontera 2 ( Ciudad / Estado )    7859
Stop de Frontera 3 ( Ciudad / Estado )    7908
Billing Ref                               7916
PU Number                                 7916
Accesorios                                7916
Razón de cancelación                      7916
Número de factura                          596
Tipo de Equipo                             356
Número de Comentarios Ops Rep             7870
Fecha Subida Factura Proveedor            4323
All in rate venta                          147
All in rate costo                          147
Accesorial venta                           147
Accesorial costo                           147
Cantidad Accesoriales Venta                147
Cantidad Accesoriales Costo                147
dtype: int64

In [14]:
df = df.drop(columns=["Razón de cancelación", "Venta Perdida", "Numero de Comentarios"])

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 7916 entries, 13 to 8713
Data columns (total 63 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   VXS                                     7916 non-null   str
 1   LINK                                    7916 non-null   str
 2   Cliente                                 7916 non-null   str
 3   Carrier                                 7513 non-null   str
 4   ORIGEN                                  7770 non-null   str
 5   DESTINO                                 7770 non-null   str
 6   DIVISION                                7773 non-null   str
 7   RANGO                                   7698 non-null   str
 8   FLUJO                                   6970 non-null   str
 9   ESTATUS                                 7916 non-null   str
 10  VENTA                                   7769 non-null   str
 11  COSTO                                   7769 non-null   str
 12  UTILIDAD                                7694 non-null   str
 13  VENTA EN MXN                            7769 non-null   str
 14  COSTO EN MXN                            7769 non-null   str
 15  UTILIDAD EN MXN                         7694 non-null   str
 16  FECHA CREACIÓN                          7916 non-null   str
 17  Fecha programada de recolección         7749 non-null   str
 18  Fecha programada de entrega             7749 non-null   str
 19  Fecha Booked                            7720 non-null   str
 20  Fecha Dispatched                        7607 non-null   str
 21  Fecha At Shipper                        7608 non-null   str
 22  Fecha Picked Up                         7581 non-null   str
 23  Fecha At Border                         7556 non-null   str
 24  Fecha In Transit                        7513 non-null   str
 25  Fecha At Delivery                       7485 non-null   str
 26  Fecha Delivered                         7483 non-null   str
 27  Fecha Ready to Invoice                  6055 non-null   str
 28  FECHA DE FACTURA                        7320 non-null   str
 29  OTP                                     7916 non-null   int64
 30  OTD                                     7916 non-null   int64
 31  CXB                                     7916 non-null   int64
 32  National                                7916 non-null   int64
 33  SALES REP                               7682 non-null   str
 34  OPS REP                                 7914 non-null   str
 35  CARRIER REP                             7709 non-null   str
 36  AFTERHOURS REP                          4441 non-null   str
 37  SALES LEAD                              1575 non-null   str
 38  OPS LEAD                                7914 non-null   str
 39  CARRIER LEAD                            7700 non-null   str
 40  SALES MANAGER                           7884 non-null   str
 41  OPS MANAGER                             7914 non-null   str
 42  CARRIER MANAGER                         7709 non-null   str
 43  Stop de Frontera 1 ( Ciudad / Estado )  491 non-null    str
 44  Stop de Frontera 2 ( Ciudad / Estado )  57 non-null     str
 45  Stop de Frontera 3 ( Ciudad / Estado )  8 non-null      str
 46  Billing Ref                             0 non-null      float64
 47  PU Number                               0 non-null      float64
 48  Accesorios                              0 non-null      float64
 49  Número de factura                       7320 non-null   str
 50  Tipo de Equipo                          7560 non-null   str
 51  Total Comentarios                       7916 non-null   int64
 52  Calificación del servicio del carrier   7916 non-null   str
 53  Número de Comentarios Ops Rep           46 non-null     float64
 54  Origen Tardio                           7916 non-null   int64
 55  Destino Tardio                          7916 non-null   int64
 56  Fecha Subida Factura Proveedor          3593 non-null   str
 57  All in rate venta                       7769 non-null   str
 58  All in rate costo                       7769 non-null   str
 59  Accesorial venta                        7769 non-null   str
 60  Accesorial costo                        7769 non-null   str
 61  Cantidad Accesoriales Venta             7769 non-null   float64
 62  Cantidad Accesoriales Costo             7769 non-null   float64
dtypes: float64(6), int64(7), str(50)
memory usage: 3.9 MB

In [16]:
df["SALES LEAD"].unique()

<StringArray>
[nan, 'Blanca Rodríguez']
Length: 2, dtype: str

In [17]:
# Al solo existir como valor Blanca Rodriguez en la columna "SALES LEAD", se elimina la columna
df = df.drop(columns=["SALES LEAD"])

In [18]:
df["ESTATUS"].unique()

<StringArray>
[             'Invoiced', 'Delivered Without POD',                  'Hold',
                 'Draft',      'Ready to Invoice',            'In Transit',
             'At Border',             'Delivered',             'Picked Up',
                'Booked',            'At Shipper',             'Available',
           'At Delivery',            'Dispatched']
Length: 14, dtype: str

In [19]:
df = df.drop(columns=["Accesorios"])

In [20]:
#Eliminar filas donde en la columna "ESTATUS" aparezca "Draft" o "Hold"
df = df[~df["ESTATUS"].isin(["Draft", "Hold"])]

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 7736 entries, 13 to 8713
Data columns (total 61 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   VXS                                     7736 non-null   str
 1   LINK                                    7736 non-null   str
 2   Cliente                                 7736 non-null   str
 3   Carrier                                 7505 non-null   str
 4   ORIGEN                                  7736 non-null   str
 5   DESTINO                                 7736 non-null   str
 6   DIVISION                                7736 non-null   str
 7   RANGO                                   7661 non-null   str
 8   FLUJO                                   6940 non-null   str
 9   ESTATUS                                 7736 non-null   str
 10  VENTA                                   7735 non-null   str
 11  COSTO                                   7735 non-null   str
 12  UTILIDAD                                7660 non-null   str
 13  VENTA EN MXN                            7735 non-null   str
 14  COSTO EN MXN                            7735 non-null   str
 15  UTILIDAD EN MXN                         7660 non-null   str
 16  FECHA CREACIÓN                          7736 non-null   str
 17  Fecha programada de recolección         7735 non-null   str
 18  Fecha programada de entrega             7735 non-null   str
 19  Fecha Booked                            7711 non-null   str
 20  Fecha Dispatched                        7603 non-null   str
 21  Fecha At Shipper                        7605 non-null   str
 22  Fecha Picked Up                         7579 non-null   str
 23  Fecha At Border                         7554 non-null   str
 24  Fecha In Transit                        7511 non-null   str
 25  Fecha At Delivery                       7485 non-null   str
 26  Fecha Delivered                         7483 non-null   str
 27  Fecha Ready to Invoice                  6055 non-null   str
 28  FECHA DE FACTURA                        7320 non-null   str
 29  OTP                                     7736 non-null   int64
 30  OTD                                     7736 non-null   int64
 31  CXB                                     7736 non-null   int64
 32  National                                7736 non-null   int64
 33  SALES REP                               7673 non-null   str
 34  OPS REP                                 7734 non-null   str
 35  CARRIER REP                             7700 non-null   str
 36  AFTERHOURS REP                          4334 non-null   str
 37  OPS LEAD                                7734 non-null   str
 38  CARRIER LEAD                            7691 non-null   str
 39  SALES MANAGER                           7704 non-null   str
 40  OPS MANAGER                             7734 non-null   str
 41  CARRIER MANAGER                         7700 non-null   str
 42  Stop de Frontera 1 ( Ciudad / Estado )  488 non-null    str
 43  Stop de Frontera 2 ( Ciudad / Estado )  56 non-null     str
 44  Stop de Frontera 3 ( Ciudad / Estado )  8 non-null      str
 45  Billing Ref                             0 non-null      float64
 46  PU Number                               0 non-null      float64
 47  Número de factura                       7320 non-null   str
 48  Tipo de Equipo                          7526 non-null   str
 49  Total Comentarios                       7736 non-null   int64
 50  Calificación del servicio del carrier   7736 non-null   str
 51  Número de Comentarios Ops Rep           46 non-null     float64
 52  Origen Tardio                           7736 non-null   int64
 53  Destino Tardio                          7736 non-null   int64
 54  Fecha Subida Factura Proveedor          3592 non-null   str
 55  All in rate venta                       7735 non-null   str
 56  All in rate costo                       7735 non-null   str
 57  Accesorial venta                        7735 non-null   str
 58  Accesorial costo                        7735 non-null   str
 59  Cantidad Accesoriales Venta             7735 non-null   float64
 60  Cantidad Accesoriales Costo             7735 non-null   float64
dtypes: float64(5), int64(7), str(49)
memory usage: 3.7 MB

In [22]:
# Mostrar ESTATUS del valor vacio en la columna VENTA y COSTO
df[df["VENTA"].isnull() | df["COSTO"].isnull()]

,VXS,LINK,Cliente,Carrier,ORIGEN,DESTINO,DIVISION,RANGO,FLUJO,ESTATUS,...,Número de Comentarios Ops Rep,Origen Tardio,Destino Tardio,Fecha Subida Factura Proveedor,All in rate venta,All in rate costo,Accesorial venta,Accesorial costo,Cantidad Accesoriales Venta,Cantidad Accesoriales Costo
630,VXS-06858,https://zenitt.xyz/admin/create-load?id=1069,Cliente 28,Carrier 31,"Lázaro Cárdenas, Michoacán de Ocampo","Coatzacoalcos, Veracruz de Ignacio de la Llave",Domestic,Spot,Southbound,Invoiced,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.columns

Index(['VXS', 'LINK', 'Cliente', 'Carrier', 'ORIGEN', 'DESTINO', 'DIVISION',
       'RANGO', 'FLUJO', 'ESTATUS', 'VENTA', 'COSTO', 'UTILIDAD',
       'VENTA EN MXN', 'COSTO EN MXN', 'UTILIDAD EN MXN', 'FECHA CREACIÓN',
       'Fecha programada de recolección', 'Fecha programada de entrega',
       'Fecha Booked', 'Fecha Dispatched', 'Fecha At Shipper',
       'Fecha Picked Up', 'Fecha At Border', 'Fecha In Transit',
       'Fecha At Delivery', 'Fecha Delivered', 'Fecha Ready to Invoice',
       'FECHA DE FACTURA', 'OTP', 'OTD', 'CXB', 'National', 'SALES REP',
       'OPS REP', 'CARRIER REP', 'AFTERHOURS REP', 'OPS LEAD', 'CARRIER LEAD',
       'SALES MANAGER', 'OPS MANAGER', 'CARRIER MANAGER',
       'Stop de Frontera 1 ( Ciudad / Estado )',
       'Stop de Frontera 2 ( Ciudad / Estado )',
       'Stop de Frontera 3 ( Ciudad / Estado )', 'Billing Ref', 'PU Number',
       'Número de factura', 'Tipo de Equipo', 'Total Comentarios',
       'Calificación del servicio del carrier',
       'Número de Comentarios Ops Rep', 'Origen Tardio', 'Destino Tardio',
       'Fecha Subida Factura Proveedor', 'All in rate venta',
       'All in rate costo', 'Accesorial venta', 'Accesorial costo',
       'Cantidad Accesoriales Venta', 'Cantidad Accesoriales Costo'],
      dtype='str')

### Dividir entre columnas inecesarias y columanas necesarias.

Esto se hace con el propósito de facilitar y agilizar el proceso de selección de columnas.

In [24]:
# Dividir el dataset en columnas útiles, columnas trash y columnas dudosas
columns_trash = ["VXS","LINK", "VENTA", "COSTO", "UTILIDAD", "PU Number", "Billing Ref", "Número de factura", "Total Comentarios", 
                 "Calificación del servicio del carrier", "Número de Comentarios Ops Rep", 'Fecha Dispatched', 
                 'Fecha At Shipper', 'Fecha At Border', 'Fecha In Transit','Fecha At Delivery', 'Fecha Delivered', 
                 'Fecha Ready to Invoice','FECHA DE FACTURA', 'Fecha Subida Factura Proveedor']

columns_doubtful = [ "OTP", "OTD", 'All in rate venta', 'All in rate costo', 
                    'OPS REP', 'CARRIER REP', 'AFTERHOURS REP', 'OPS LEAD', 'CARRIER LEAD', 'OPS MANAGER', 'CARRIER MANAGER', 
                    'Origen Tardio', 'Destino Tardio', 'Fecha Picked Up', 'ESTATUS', 'Accesorial costo', 'Cantidad Accesoriales Costo']

columns_useful = [col for col in df.columns if col not in columns_trash and col not in columns_doubtful]

In [25]:
columns_useful

['Cliente',
 'Carrier',
 'ORIGEN',
 'DESTINO',
 'DIVISION',
 'RANGO',
 'FLUJO',
 'VENTA EN MXN',
 'COSTO EN MXN',
 'UTILIDAD EN MXN',
 'FECHA CREACIÓN',
 'Fecha programada de recolección',
 'Fecha programada de entrega',
 'Fecha Booked',
 'CXB',
 'National',
 'SALES REP',
 'SALES MANAGER',
 'Stop de Frontera 1 ( Ciudad / Estado )',
 'Stop de Frontera 2 ( Ciudad / Estado )',
 'Stop de Frontera 3 ( Ciudad / Estado )',
 'Tipo de Equipo',
 'Accesorial venta',
 'Cantidad Accesoriales Venta']

### Limpiar el Dataset después de eliminar las columnas no necesarias

In [26]:
# Usar solo las columnas útiles para el dtaframe
df = df[columns_useful]
df.info()

<class 'pandas.DataFrame'>
Index: 7736 entries, 13 to 8713
Data columns (total 24 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cliente                                 7736 non-null   str
 1   Carrier                                 7505 non-null   str
 2   ORIGEN                                  7736 non-null   str
 3   DESTINO                                 7736 non-null   str
 4   DIVISION                                7736 non-null   str
 5   RANGO                                   7661 non-null   str
 6   FLUJO                                   6940 non-null   str
 7   VENTA EN MXN                            7735 non-null   str
 8   COSTO EN MXN                            7735 non-null   str
 9   UTILIDAD EN MXN                         7660 non-null   str
 10  FECHA CREACIÓN                          7736 non-null   str
 11  Fecha programada de recolección         7735 non-null   str
 12  Fecha programada de entrega             7735 non-null   str
 13  Fecha Booked                            7711 non-null   str
 14  CXB                                     7736 non-null   int64
 15  National                                7736 non-null   int64
 16  SALES REP                               7673 non-null   str
 17  SALES MANAGER                           7704 non-null   str
 18  Stop de Frontera 1 ( Ciudad / Estado )  488 non-null    str
 19  Stop de Frontera 2 ( Ciudad / Estado )  56 non-null     str
 20  Stop de Frontera 3 ( Ciudad / Estado )  8 non-null      str
 21  Tipo de Equipo                          7526 non-null   str
 22  Accesorial venta                        7735 non-null   str
 23  Cantidad Accesoriales Venta             7735 non-null   float64
dtypes: float64(1), int64(2), str(21)
memory usage: 1.5 MB

In [27]:
# valores nulos por columna
df.isnull().sum()

Cliente                                      0
Carrier                                    231
ORIGEN                                       0
DESTINO                                      0
DIVISION                                     0
RANGO                                       75
FLUJO                                      796
VENTA EN MXN                                 1
COSTO EN MXN                                 1
UTILIDAD EN MXN                             76
FECHA CREACIÓN                               0
Fecha programada de recolección              1
Fecha programada de entrega                  1
Fecha Booked                                25
CXB                                          0
National                                     0
SALES REP                                   63
SALES MANAGER                               32
Stop de Frontera 1 ( Ciudad / Estado )    7248
Stop de Frontera 2 ( Ciudad / Estado )    7680
Stop de Frontera 3 ( Ciudad / Estado )    7728
Tipo de Equipo                             210
Accesorial venta                             1
Cantidad Accesoriales Venta                  1
dtype: int64

In [28]:
# Al tener tantos valores nulos en las fronteras, se decien eliminar las columnas que contienen la palabra Stop
df = df.drop(columns=[col for col in df.columns if "Stop" in col])

In [29]:
# Eliminar las filas que tengan valores nulos en las columnas de Venta y costo
df = df.dropna(subset=["VENTA EN MXN", "COSTO EN MXN"])

In [30]:
df.isnull().sum()

Cliente                              0
Carrier                            231
ORIGEN                               0
DESTINO                              0
DIVISION                             0
RANGO                               75
FLUJO                              796
VENTA EN MXN                         0
COSTO EN MXN                         0
UTILIDAD EN MXN                     75
FECHA CREACIÓN                       0
Fecha programada de recolección      1
Fecha programada de entrega          1
Fecha Booked                        25
CXB                                  0
National                             0
SALES REP                           63
SALES MANAGER                       32
Tipo de Equipo                     210
Accesorial venta                     0
Cantidad Accesoriales Venta          0
dtype: int64

In [31]:
# Funcion para reemplazar valores nulos de una columna agregando la palabra "Unknown" al valor
def replace_unknown(column):
    df[column] = df[column].fillna("Unknown")

In [32]:
replace_unknown("Carrier")
replace_unknown("RANGO")
replace_unknown("FLUJO")
replace_unknown("Tipo de Equipo")
replace_unknown("SALES REP")
replace_unknown("SALES MANAGER")

In [33]:
df["RANGO"].unique()

<StringArray>
['Contracted', 'Unknown', 'Spot', 'Backup']
Length: 4, dtype: str

In [34]:
df.isnull().sum()

Cliente                             0
Carrier                             0
ORIGEN                              0
DESTINO                             0
DIVISION                            0
RANGO                               0
FLUJO                               0
VENTA EN MXN                        0
COSTO EN MXN                        0
UTILIDAD EN MXN                    75
FECHA CREACIÓN                      0
Fecha programada de recolección     1
Fecha programada de entrega         1
Fecha Booked                       25
CXB                                 0
National                            0
SALES REP                           0
SALES MANAGER                       0
Tipo de Equipo                      0
Accesorial venta                    0
Cantidad Accesoriales Venta         0
dtype: int64

In [35]:
# Eliminar las filas que tengan nulos en las fechas
df = df.dropna(subset=['Fecha programada de recolección', 'Fecha programada de entrega', 'Fecha Booked'])

In [36]:
df.isnull().sum()

Cliente                             0
Carrier                             0
ORIGEN                              0
DESTINO                             0
DIVISION                            0
RANGO                               0
FLUJO                               0
VENTA EN MXN                        0
COSTO EN MXN                        0
UTILIDAD EN MXN                    75
FECHA CREACIÓN                      0
Fecha programada de recolección     0
Fecha programada de entrega         0
Fecha Booked                        0
CXB                                 0
National                            0
SALES REP                           0
SALES MANAGER                       0
Tipo de Equipo                      0
Accesorial venta                    0
Cantidad Accesoriales Venta         0
dtype: int64

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 7709 entries, 13 to 8693
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Cliente                          7709 non-null   str
 1   Carrier                          7709 non-null   str
 2   ORIGEN                           7709 non-null   str
 3   DESTINO                          7709 non-null   str
 4   DIVISION                         7709 non-null   str
 5   RANGO                            7709 non-null   str
 6   FLUJO                            7709 non-null   str
 7   VENTA EN MXN                     7709 non-null   str
 8   COSTO EN MXN                     7709 non-null   str
 9   UTILIDAD EN MXN                  7634 non-null   str
 10  FECHA CREACIÓN                   7709 non-null   str
 11  Fecha programada de recolección  7709 non-null   str
 12  Fecha programada de entrega      7709 non-null   str
 13  Fecha Booked                     7709 non-null   str
 14  CXB                              7709 non-null   int64
 15  National                         7709 non-null   int64
 16  SALES REP                        7709 non-null   str
 17  SALES MANAGER                    7709 non-null   str
 18  Tipo de Equipo                   7709 non-null   str
 19  Accesorial venta                 7709 non-null   str
 20  Cantidad Accesoriales Venta      7709 non-null   float64
dtypes: float64(1), int64(2), str(18)
memory usage: 1.3 MB

In [38]:
df["VENTA EN MXN"] = df["VENTA EN MXN"].str.replace("$", "")
df["VENTA EN MXN"] = df["VENTA EN MXN"].str.replace(",", "").astype(float)

In [39]:
df["COSTO EN MXN"] = df["COSTO EN MXN"].str.replace('$', '')
df["COSTO EN MXN"] = df["COSTO EN MXN"].str.replace(',', '').astype(float)

In [40]:
df["UTILIDAD EN MXN"] = df["UTILIDAD EN MXN"].str.replace('$', '')
df["UTILIDAD EN MXN"] = df["UTILIDAD EN MXN"].str.replace(',', '').astype(float)

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 7709 entries, 13 to 8693
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Cliente                          7709 non-null   str
 1   Carrier                          7709 non-null   str
 2   ORIGEN                           7709 non-null   str
 3   DESTINO                          7709 non-null   str
 4   DIVISION                         7709 non-null   str
 5   RANGO                            7709 non-null   str
 6   FLUJO                            7709 non-null   str
 7   VENTA EN MXN                     7709 non-null   float64
 8   COSTO EN MXN                     7709 non-null   float64
 9   UTILIDAD EN MXN                  7634 non-null   float64
 10  FECHA CREACIÓN                   7709 non-null   str
 11  Fecha programada de recolección  7709 non-null   str
 12  Fecha programada de entrega      7709 non-null   str
 13  Fecha Booked                     7709 non-null   str
 14  CXB                              7709 non-null   int64
 15  National                         7709 non-null   int64
 16  SALES REP                        7709 non-null   str
 17  SALES MANAGER                    7709 non-null   str
 18  Tipo de Equipo                   7709 non-null   str
 19  Accesorial venta                 7709 non-null   str
 20  Cantidad Accesoriales Venta      7709 non-null   float64
dtypes: float64(4), int64(2), str(15)
memory usage: 1.3 MB

In [42]:
df["Tipo de Equipo"].unique()

<StringArray>
[               'DryVan 53',                  'Unknown',
                      '3.5',                   'Torton',
               'Flatbed 40',          'DryVan / Reefer',
                    'Rabón',               'Flatbed 53',
        'Full Container 40',                      'LTL',
      'Single Container 40',        'Full Container 20',
               'Flatbed 48',                'Hazmat 53',
                      '1.5',      'Single Container 20',
          'Full Flatbed 40',                'Reefer 53',
              'Stepdeck 53',           'Torton Abierto',
            'Rabón Abierto', 'Full Container Reefer 40']
Length: 22, dtype: str

In [ ]:
import pandas as pd
import googlemaps
import time
import os

API_KEY = "TU_API_KEY"
gmaps = googlemaps.Client(key=API_KEY)

archivo_cache = "distancias_rutas_google.csv"

rutas = df[['ORIGEN', 'DESTINO', 'National']].drop_duplicates().copy()

print("Rutas únicas:", len(rutas))

def construir_direccion(lugar, national):
    lugar = str(lugar)

    if national == True or str(national).upper() in ['TRUE', 'YES', 'SI', 'SÍ', 'NACIONAL']:
        direccion = lugar + ", Mexico"
    else:
        direccion = lugar

    return direccion


if os.path.exists(archivo_cache):

    rutas_distancias = pd.read_csv(archivo_cache)

else:

    distancias_km = []
    duraciones_min = []

    for i in range(len(rutas)):

        origen = construir_direccion(
            rutas.iloc[i]['ORIGEN'],
            rutas.iloc[i]['National']
        )

        destino = construir_direccion(
            rutas.iloc[i]['DESTINO'],
            rutas.iloc[i]['National']
        )

        resultado = gmaps.distance_matrix(
            origins=[origen],
            destinations=[destino],
            mode="driving",
            units="metric",
            language="es"
        )

        status_general = resultado['status']
        status_ruta = resultado['rows'][0]['elements'][0]['status']

        if status_general == "OK" and status_ruta == "OK":
            distancia_metros = resultado['rows'][0]['elements'][0]['distance']['value']
            duracion_segundos = resultado['rows'][0]['elements'][0]['duration']['value']

            distancias_km.append(distancia_metros / 1000)
            duraciones_min.append(duracion_segundos / 60)

        else:
            distancias_km.append(None)
            duraciones_min.append(None)

        time.sleep(0.1)

    rutas['distancia_km'] = distancias_km
    rutas['duracion_min'] = duraciones_min

    rutas.to_csv(archivo_cache, index=False)
    rutas_distancias = rutas.copy()

df = df.merge(
    rutas_distancias,
    on=['ORIGEN', 'DESTINO', 'National'],
    how='left'
)

In [43]:
# convertir df en un csv
df.to_csv('../Data/TEC Loadboard - BD V1 Limpio.csv', index=False)